SELECT
    ---Accounting
    ----ASPA.SET_OF_BOOKS_ID,
    ---ASPA.ORG_ID,
    HOU.NAME,
    (SELECT CONCATENATED_SEGMENTS FROM GL_CODE_COMBINATIONS_KFV WHERE CODE_COMBINATION_ID = CODE_COMBINATION_ID_GAIN) "Realized Gains Acc",
    (SELECT CONCATENATED_SEGMENTS FROM GL_CODE_COMBINATIONS_KFV WHERE CODE_COMBINATION_ID = CODE_COMBINATION_ID_LOSS) "Realized Loss Acc",
    (SELECT CONCATENATED_SEGMENTS FROM GL_CODE_COMBINATIONS_KFV WHERE CODE_COMBINATION_ID = LOCATION_TAX_ACCOUNT) "Tax Acc ",
    (SELECT CONCATENATED_SEGMENTS FROM GL_CODE_COMBINATIONS_KFV WHERE CODE_COMBINATION_ID = UNALLOCATED_REVENUE_CCID) "Unallocated Rev Acc",
    CROSS_CURRENCY_RATE_TYPE,
    (SELECT CONCATENATED_SEGMENTS FROM GL_CODE_COMBINATIONS_KFV WHERE CODE_COMBINATION_ID = CODE_COMBINATION_ID_ROUND) "Cross Currnecy Rounding Acc",
    (SELECT CONCATENATED_SEGMENTS FROM GL_CODE_COMBINATIONS_KFV WHERE CODE_COMBINATION_ID = TRX_HEADER_ROUND_CCID) "Header Rounding Acc",
    DECODE(CREATE_DETAILED_DIST_FLAG,'Y','Yes','N','No') CREATE_DETAILED_DIST,
    DECODE(RUN_GL_JOURNAL_IMPORT_FLAG,'Y','Yes','N','No')  "Automatic Journal Import",
    DECODE(TRX_HEADER_LEVEL_ROUNDING,'Y','Yes','N','No') "Header Level Rounding",
    POSTING_DAYS_PER_CYCLE,
    --Trans and customer
    DECODE(CHANGE_PRINTED_INVOICE_FLAG,'Y','Yes','N','No') "Allow Change to Printed Trans",
    DECODE(INVOICE_DELETION_FLAG,'Y','Yes','N','No') "Allow Trans Deletion",
    DECODE(PAY_UNRELATED_INVOICES_FLAG,'Y','Yes','N','No') "Alw Payment of Unrelated Trans",
    DECODE(SHOW_BILLING_NUMBER_FLAG,'Y','Yes','N','No') SHOW_BILLING_NUMBER,
    DECODE(DOCUMENT_SEQ_GEN_LEVEL,'null','None','WHEN_TRX_COMPLETED','When completed','WHEN_TRX_COMMITTED','When saved') "Doc Number Generation Level",
    DECODE(ALLOW_LATE_CHARGES,'Y','Yes','N','No') "Assess Late Charge",
    ARL1.MEANING "Balance Calculation",
    ARL2.MEANING "Calculation Period",
    LATE_CHARGE_INV_TYPE_ID "Int Invoice Trans Type",
    LATE_CHARGE_DM_TYPE_ID "DM Charge Trans Type",
    FINCHRG_RECEIVABLES_TRX_ID "Interest Charge Activity",
    PENALTY_REC_TRX_ID "Penalty Charge Activity",
    LATE_CHARGE_BATCH_SOURCE_ID "Late Charge Batch Source",
    DECODE(DEFAULT_RCT_MTHD_FOR_LC_INV,'Y','Yes','N','No') "Def Receipt Method for Int Inv",
    DECODE(AI_PURGE_INTERFACE_TABLES_FLAG,'Y','Yes','N','No') PURGE_INTERFACE_TABLES,
    AI_MAX_MEMORY_IN_BYTES "Max Memory",
    AI_LOG_FILE_MESSAGE_LEVEL "Log File Msg Level",
    AI_ACCT_FLEX_KEY_LEFT_PROMPT "Accounting Flex",
    AI_MTL_ITEMS_KEY_LEFT_PROMPT "System Items",
    AI_TERRITORY_KEY_LEFT_PROMPT "Territory",
    DECODE(GENERATE_CUSTOMER_NUMBER,'Y','Yes','N','No') "Auto Customer Numb",
    DECODE(AUTO_SITE_NUMBERING,'Y','Yes','N','No') "Auto Customer Numb",
    DECODE(CREATE_RECIPROCAL_FLAG,'Y','Yes','N','No') "Create Reciprocal Customer",
    RGR.NAME "Grouping",
    --Claims
    DECODE(MATCHED_CLAIM_CREATION_FLAG,'Y','Yes','N','No') "Prepare for Claim Creation",
    DECODE(MATCHED_CLAIM_EXCL_CM_FLAG,'Y','Yes','N','No') "Exclude Credit Memos",
    --Miscellaneous
    CER_SPLIT_AMOUNT "Split Amount"
FROM
    AR_SYSTEM_PARAMETERS_ALL ASPA   ,
    HR_OPERATING_UNITS HOU          ,
    AR_LOOKUPS ARL1                 ,
    AR_LOOKUPS ARL2                 ,
    RA_GROUPING_RULES RGR
WHERE
    ASPA.ORG_ID             =   HOU.ORGANIZATION_ID
AND ARL1.LOOKUP_TYPE(+)     =   'AR_POST_BILLING_ITEM_INCLUSION'
AND ARL1.LOOKUP_CODE(+)     =   ASPA.POST_BILLING_ITEM_INCLUSION
AND ARL2.LOOKUP_TYPE(+)     =   'AR_CALCULATION_RUNNING_MODE'
AND ARL2.LOOKUP_CODE(+)     =   ASPA.LATE_CHARGE_BILLING_CALC_MODE
AND TRUNC(sysdate) BETWEEN RGR.start_date AND NVL(RGR.end_date,TRUNC(sysdate)) 
AND RGR.GROUPING_RULE_ID(+) =   ASPA.DEFAULT_GROUPING_RULE_ID
ORDER BY HOU.NAME;